name: Delete Artifacts Update Checker

on:
  #release:
  #  types: published
 # schedule:
  #  - cron: 20 0/1 * * * 
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  New-Update-Files:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        token: ${{ secrets.GH_TOKEN }}
        
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        echo "starttime=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
   
    
    - name: Total time
      run: |
         endtime=`date +'%Y-%m-%d %H:%M:%S'`
         start_seconds=$(date --date="$starttime" +%s)
         end_seconds=$(date --date="$endtime" +%s)
         seconds=$(( end_seconds-start_seconds )
         hour=$(( $seconds/3600 ))
         min=$(( ($seconds-${hour}*3600)/60 ))
         sec=$(( $seconds-${hour}*3600-${min}*60 ))
         echo $seconds
         echo $starttime
         echo $endtime
         echo "time1=${hour}:${min}:${sec}" >> $GITHUB_ENV
             
    - name: Telegram notification upload success
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
           Ò‰ ğŸ¡åŒæ­¥æˆåŠŸ Ò‰
           ç¼–è¯‘è€—æ—¶ï¼š${{ env.time }}æ—¶${{ env.time1 }}åˆ†
