name: Build X86_64 OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      url:
        description: "URL connection to Actions"
        required: false
        default: "https://github.com/coolsnowwolf/lede.git"
        type: choice
        options:
          - https://github.com/coolsnowwolf/lede.git
          - https://github.com/Lienol/openwrt.git
          - https://github.com/openwrt/openwrt.git
      branch:
        description: "BRANCH connection to Actions"
        required: false
        default: "master"
        type: choice
        options:
          - master
          - main
          - openwrt-18.06
          - openwrt-21.02
          - openwrt-22.03
      config:
        description: "config connection to Actions"
        required: false
        default: "x86/.config"  
  #schedule:
    #- cron: 15 16 * * *

env:
  REPO_URL: ${{ github.event.inputs.url }}
  REPO_BRANCH: ${{ github.event.inputs.branch }}
  FEEDS_CONF: x86/feeds.conf.default
  CONFIG_FILE: ${{ github.event.inputs.config }}
  DIY_P1_SH: x86/diy1.sh
  DIY_P2_SH: x86/diy2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: false
  TZ: Asia/Shanghai
  FILE_NAME: X86_64
  PRODUCT_NAME: x86_64
  CONFIG: X86

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check server configuration æŸ¥çœ‹æœåŠ¡å™¨
      run: |
        echo -e "-------------- ------------CPUä¿¡æ¯------------------------------------------\n"
        echo "CPUç‰©ç†æ•°é‡:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
        echo -e "CPUæ ¸å¿ƒåŠç‰ˆæœ¬ä¿¡æ¯ï¼š$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "-------------------------------å†…å­˜ä¿¡æ¯-------------------------------------------"
        echo "å·²å®‰è£…å†…å­˜è¯¦ç»†ä¿¡æ¯ï¼š"
        sudo lshw -short -C memory | grep GiB
        echo -e "\n"
        echo "-----------------------------ç¡¬ç›˜ä¿¡æ¯---------------------------------------------"
        echo -e  "ç¡¬ç›˜æ•°é‡ï¼š$(ls /dev/sd* | grep -v [1-9] | wc -l) \n"
        echo "ç¡¬ç›˜è¯¦æƒ…ï¼š"
        echo " ç³»ç»Ÿç©ºé—´       ç±»åž‹     æ€»æ•°   å·²ç”¨  å¯ç”¨ ä½¿ç”¨çŽ‡"
        df -Th
        
    - name: Initialization environment åˆå§‹åŒ–ç³»ç»ŸçŽ¯å¢ƒ
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E swapoff -a
        sudo -E rm -f /swapfile
        sudo -E docker image prune -a -f
        sudo -E snap set system refresh.retain=2
        sudo -E apt-get -y purge azure* dotnet* firefox ghc* google* hhvm llvm* mono* mysql* openjdk* php* zulu*
        sudo -E apt-get -y autoremove --purge
        sudo -E rm -rf /usr/share/dotnet /usr/local/lib/android/sdk /etc/mysql /etc/php /usr/local/share/boost
        [ -n "$AGENT_TOOLSDIRECTORY" ] && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo -E apt-get update -y
        sudo -E apt-get install -y build-essential rsync asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python3 python3-pip python3-ply haveged lrzsz device-tree-compiler scons
        wget -qO - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | sed 's/python-/python3-/g' | /bin/bash
        pip install aligo
        sudo -E apt-get clean
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
        df -h
        
    - name: Clone source code ä¸‹è½½æºç 
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt 
        Author=$(git show -s --date=short --format="%an")
        Date=$(git show -s --date=short --format="%ci")
        Commit=$(git show -s --date=short --format="%s")
        Hash=$(git show -s --date=short --format="%H")
        echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV
        echo "author=$Author" >> $GITHUB_ENV
        echo "date=$Date" >> $GITHUB_ENV
        echo "commit=$Commit" >> $GITHUB_ENV
        echo "hash=$Hash" >> $GITHUB_ENV
        
    - name: Start time ç¼–è¯‘å¼€å§‹æ—¶é—´
      run: |  
        echo "ç¼–è¯‘å¼€å§‹æ—¶é—´..."
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "start=$(date +%s)" >> $GITHUB_ENV

    - name: Load custom feeds è‡ªå®šä¹‰DIY1é…ç½®
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH
        
    - name: Update & Install feeds æ›´æ–°å¹¶å®‰è£…é…ç½®ä¸­çš„æº
      working-directory: ./openwrt
      run: |
          ./scripts/feeds update -a 
          
          ./scripts/feeds install -a
          
    - name: Custom configuration è‡ªå®šä¹‰DIY2é…ç½®
      run: |  
          chmod +x $DIY_P2_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P2_SH
          sed -i "s/KERNEL_PATCHVER:=*.*/KERNEL_PATCHVER:=5.15/g" target/linux/x86/Makefile
          
    - name: Load custom configuration åŠ è½½configé…ç½®
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        cd openwrt && make defconfig
        
    - name: Output compilation information è¾“å‡ºç¼–è¯‘ä¿¡æ¯
      run: |
          cd openwrt
          echo " ç³»ç»Ÿç©ºé—´       ç±»åž‹  æ€»æ•°  å·²ç”¨  å¯ç”¨ ä½¿ç”¨çŽ‡"
          df -hT $PWD
          echo
          echo "=========================================="
          grep -i CONFIG_PACKAGE_luci-app .config | grep  -v \# > Plug-in
          grep -i CONFIG_PACKAGE_luci-theme .config | grep  -v \# >> Plug-in
          sed -i '/INCLUDE/d' Plug-in > /dev/null 2>&1
          sed -i 's/CONFIG_PACKAGE_/ã€/g' Plug-in
          sed -i '/Transparent_Proxy/d' Plug-in > /dev/null 2>&1
          sed -i 's/=y/\ /g' Plug-in
          awk '$0=NR$0' Plug-in > Plug-2
          awk '{print "	" $0}' Plug-2 > Plug-in    
          echo
          echo
          echo "	      å·²é€‰æ’ä»¶åˆ—è¡¨"
          cat Plug-in
          rm -rf {Plug-in,Plug-2}  
          echo
          echo "=========================================="
          echo
          echo
          echo "è¾“å‡ºå®Œæ•´æ’ä»¶ä¿¡æ¯..."
          echo
          echo
          cat .config

    - name: Download package ä¸‹è½½å›ºä»¶åŒ…
      working-directory: ./openwrt
      id: package
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Compile the firmware å¼€å§‹ç¼–è¯‘å›ºä»¶
      working-directory: ./openwrt
      id: compile
      run: |
        echo -e ">>>> $(nproc) thread compile ..."
        make -j$(nproc) || make -j1 V=s
        echo "::set-output name=status::success"
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        
    - name: Check space usage æ£€æŸ¥ç©ºé—´ä½¿ç”¨æƒ…å†µ
      if: (!cancelled())
      run: |
        echo "=========================================="
        echo "----------------ç©ºé—´ä½¿ç”¨-------------------"
        echo "=========================================="
        echo " ç³»ç»Ÿç©ºé—´      ç±»åž‹   æ€»æ•°  å·²ç”¨  å¯ç”¨ ä½¿ç”¨çŽ‡"
        df -hT
        echo "=========================================="
        du -h --max-depth=1 openwrt/ --exclude=build_dir --exclude=bin
        du -h --max-depth=1 openwrt/build_dir
        du -h --max-depth=1 openwrt/bin

    - name: Upload bin directory ä¸Šä¼ binç›®å½•
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin
        
    - name: Delete files åˆ é™¤æ–‡ä»¶å¹¶æ”¹å
      working-directory: ./openwrt
      run: |
        rm -rf  bin/targets/x86/64/config.buildinfo
        rm -rf  bin/targets/x86/64/feeds.buildinfo
        rm -rf  bin/targets/x86/64/openwrt-x86-64-generic-kernel.bin
        rm -rf  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined-efi.vmdk
        rm -rf  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.vmdk
        rm -rf  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-rootfs.img.gz
        rm -rf  bin/targets/x86/64/openwrt-x86-64-generic.manifest
        rm -rf  bin/targets/x86/64/sha256sums
        rm -rf  bin/targets/x86/64/version.buildinfo
        sleep 2
        str1=`grep "KERNEL_PATCHVER:="  target/linux/x86/Makefile | cut -d = -f 2` #åˆ¤æ–­å½“å‰é»˜è®¤å†…æ ¸ç‰ˆæœ¬å·å¦‚5.10
        ver414=`grep "LINUX_VERSION-4.14 ="  include/kernel-4.14 | cut -d . -f 3`
        ver419=`grep "LINUX_VERSION-4.19 ="  include/kernel-4.19 | cut -d . -f 3`
        ver54=`grep "LINUX_VERSION-5.4 ="  include/kernel-5.4 | cut -d . -f 3`
        ver510=`grep "LINUX_VERSION-5.10 ="  include/kernel-5.10 | cut -d . -f 3`
        ver515=`grep "LINUX_VERSION-5.15 ="  include/kernel-5.15 | cut -d . -f 3`
        ver517=`grep "LINUX_VERSION-5.18 ="  include/kernel-5.18 | cut -d . -f 3`
        if [ "$str1" = "5.4" ];then
          mv  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img.gz       bin/targets/x86/64/openwrt_x86-64_${str1}.${ver54}_bios.img.gz
          mv  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined-efi.img.gz   bin/targets/x86/64/openwrt_x86-64_${str1}.${ver54}_uefi.img.gz
        elif [ "$str1" = "4.19" ];then
          mv  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img.gz       bin/targets/x86/64/openwrt_x86-64_${str1}.${ver419}_bios.img.gz
          mv  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined-efi.img.gz   bin/targets/x86/64/openwrt_x86-64_${str1}.${ver419}_uefi.img.gz
        elif [ "$str1" = "4.14" ];then
          mv  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img.gz       bin/targets/x86/64/openwrt_x86-64_${str1}.${ver414}_bios.img.gz
          mv  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined-efi.img.gz   bin/targets/x86/64/openwrt_x86-64_${str1}.${ver414}_uefi.img.gz
        elif [ "$str1" = "5.10" ];then
          mv  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img.gz       bin/targets/x86/64/openwrt_x86-64_${str1}.${ver510}_bios.img.gz
          mv  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined-efi.img.gz   bin/targets/x86/64/openwrt_x86-64_${str1}.${ver510}_uefi.img.gz
        elif [ "$str1" = "5.15" ];then
          mv  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img.gz       bin/targets/x86/64/openwrt_x86-64_${str1}.${ver515}_bios.img.gz
          mv  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined-efi.img.gz   bin/targets/x86/64/openwrt_x86-64_${str1}.${ver515}_uefi.img.gz       
        elif [ "$str1" = "5.18" ];then
          mv  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img.gz       bin/targets/x86/64/openwrt_x86-64_${str1}.${ver518}_bios.img.gz
          mv  bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined-efi.img.gz   bin/targets/x86/64/openwrt_x86-64_${str1}.${ver518}_uefi.img.gz     
        fi
        
    - name: Organize files ç»„ç»‡æ–‡ä»¶
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
        
    - name: Upload firmware directory ä¸Šè½½å›ºä»¶ç›®å½•
      uses: actions/upload-artifact@main
      if: env.UPLOAD_FIRMWARE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Create release åˆ›å»ºå‘å¸ƒ
      id: release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.DATE }} ã€Œ ${{ env.PRODUCT_NAME }} ã€å›ºä»¶
        allowUpdates: true
        removeArtifacts: true
        artifacts: ${{ env.FIRMWARE }}/*
        tag: ${{ env.FILE_NAME }}
        commit: main
        token: ${{ secrets.GH_TOKEN }}
        body: |
          - â­ï¸X86_64 
          - ðŸ”¥é»˜è®¤IPï¼š192.168.8.3 é»˜è®¤å¯†ç ï¼špassword
          - å½“å‰ä½¿ç”¨ç‰ˆæœ¬:ã€ç¼–è¯‘å‰çš„æœ€åŽä¸€æ¬¡[âž¦ä¸»æºç ](https://github.com/coolsnowwolf/lede)æ›´æ–°è®°å½•ã€‘
          â˜…  æ„Ÿè°¢æºç ä½œè€…æ— ç§åˆ†äº«ï¼
          ðŸŽˆ æ›´æ–°ä¿¡æ¯ï¼š
          ðŸŽˆ ä½œè€…: ${{ env.author }}
          
          ðŸŽˆ æ—¶é—´: ${{ env.date }}
          
          ðŸŽˆ å†…å®¹: ${{ env.commit }}
          
          ðŸŽˆ hash: ${{ env.hash }}
     
    - name: Completion time ç¼–è¯‘å®Œæˆæ—¶é—´
      if: steps.organizer.outputs.status == 'success' 
      run: |
         echo "ç¼–è¯‘å®Œæˆæ—¶é—´..."
         echo "DATE1=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
         end=$(date +%s)
         seconds=$(( end - start ))
         hour=$(( $seconds/3600 ))
         min=$(( ($seconds-${hour}*3600)/60 ))
         sec=$(( $seconds-${hour}*3600-${min}*60 ))
         HMS=`echo ${hour}:${min}:${sec}`
         echo "time=$HMS" >> $GITHUB_ENV
         
    - name: Telegram notification ç¼–è¯‘æˆåŠŸä¿¡æ¯é€šçŸ¥
      if: steps.organizer.outputs.status == 'success' 
      run: |
        MSG="
          â™¨ï¸${{ env.PRODUCT_NAME }}ç¼–è¯‘å®Œæˆ
          å¼€å§‹æ—¶é—´ï¼š${{ env.DATE }}
          å®Œæˆæ—¶é—´ï¼š${{ env.DATE1 }}
          ç¼–è¯‘è€—æ—¶ï¼š${{ env.time }}
          æ›´æ–°ä¿¡æ¯ï¼š
          ä½œè€…: ${{ env.author }}
          æ—¶é—´: ${{ env.date }}
          å†…å®¹: ${{ env.commit }}
          hash: ${{ env.hash }}
        "
        curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_TO }}&text=${MSG}" >/dev/null 2>&1 && echo "ok..."
